project_id = "bkurhudbqvdzhjjynqyi"

[functions.chat-assistant]
verify_jwt = false

[functions.email-generator]
verify_jwt = false

[functions.plan-generator]
verify_jwt = false

[functions.social-generator]
verify_jwt = false

[functions.pitch-creator]
verify_jwt = false

[functions.avatar-creator]
verify_jwt = false
