project_id = "bkurhudbqvdzhjjynqyi"

[functions.chat-assistant]
verify_jwt = false

[functions.email-generator]
verify_jwt = false

[functions.plan-generator]
verify_jwt = false

[functions.social-generator]
verify_jwt = false

[functions.pitch-creator]
verify_jwt = false

[functions.avatar-creator]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.export-user-data]
verify_jwt = false
